management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true

training.metrics.test.enabled=true
training.metrics.test.surefire-dir=target/surefire-reports
training.metrics.test.jacoco-xml=target/site/jacoco/jacoco.xml
training.metrics.test.refresh-interval=30000
